### PR TITLE
Include ddlite as a submodule

### PR DESCRIPTION
**Pull request by alldefector**

### CODE REVIEW

**Comment by ajratner** [comment]
I think we now include dd-biolib as a sub module of ddlite?

**Comment by alldefector** [comment]
Yeah, I also created a corresponding PR in ddlite...

I was trying to play this repo, and found that it requires quite some file copying from ddlite (and unnecessarily from treedlib). Thought that including ddlite as a submodule (and recursively treedlib) would be easier... Looks like there had been an attempt at using submodules earlier. Not sure why it was abandoned...

What's the planned relationship between this repo and ddlite? Who's whose lib??? If there is a blueprint for using the ddlite repo as a container of various apps, feel free to disregard this PR and the other...

**Comment by ajratner** [comment]
I think the idea was that this repo- dd-biolib- would be a set of
bio-specific utilities for ddlite (although they could obviously be used
outside of ddlite as well).  Hence the original plan was for dd-biolib to
be a submodule of ddlite...

Any objections to this plan?  Then we can remove the cyclic dependency in
the other direction.  I have no strong preferences either way though, so
open to doing it the other direction

**Comment by alldefector** [comment]
The cyclic dependency seems to be due to the fact that each repo has both python modules and notebooks, and the notebooks from both are going to depend on python modules from both repos...

Maybe we could adopt this pattern from FB:
https://secure.phabricator.com/book/phabricator/article/installation_guide/#installing-required-comp

Basically rely on the colocation of multiple repos. (We could do it for all three repos: treedlib, ddlite, and dd-biolib.)

If do that, we could get rid of the subdirs at the root of the repo pointing to other repos (as a submodule or otherwise).

**Comment by jason-fries** [comment]
I concur on dd-biolib being a submodule of ddlite -- that is the post-hackathon plan. As for notebooks, the ddlite examples (chemical and disease name extractors) could easily move to ether the ddlite repo or some other place.

**Comment by alldefector** [comment]
Sounds great! I'll play from the ddlite repo once they are moved :)

**Pull request closed without merging**
